# Branch Protection Policy for TelegramYtDlpBot
# This file documents the branch protection rules that should be enforced on the main branch
# 
# To apply these settings via GitHub CLI:
# gh api repos/taldelarosa/TelegramYtDlpBot/branches/master/protection -X PUT --input .github/branch-protection.yml
#
# Or apply manually via GitHub Web UI:
# Repository Settings → Branches → Add branch protection rule

# Branch name pattern
pattern: master

# Protection settings
required_status_checks:
  strict: true  # Require branches to be up to date before merging
  contexts: []  # Add CI/CD check names here when implemented (e.g., ["build", "test"])

required_pull_request_reviews:
  required_approving_review_count: 1
  dismiss_stale_reviews: true  # Dismiss approvals when new commits are pushed
  require_code_owner_reviews: false
  require_last_push_approval: false

restrictions: null  # No user/team restrictions - all can create PRs

enforce_admins: true  # Enforce rules even for admins (recommended)

required_linear_history: false  # Allow merge commits

allow_force_pushes: false  # Prevent force pushes to main

allow_deletions: false  # Prevent branch deletion

block_creations: false  # Allow branch creation

required_conversation_resolution: true  # Require all PR conversations to be resolved before merge

lock_branch: false  # Don't make branch read-only
